Minitest:
  Include:
    - '**/test/**/*'

Minitest/AssertNil:
  Description: 'This cop enforces the test to use `assert_nil` instead of using `assert_equal(nil, something)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-nil'
  Enabled: true
  VersionAdded: '0.1'

Minitest/AssertEmpty:
  Description: 'This cop enforces the test to use `assert_empty` instead of using `assert(object.empty?)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-empty'
  Enabled: true
  VersionAdded: '0.2'

Minitest/AssertIncludes:
  Description: 'This cop enforces the test to use `assert_includes` instead of using `assert(collection.include?(object))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-includes'
  Enabled: true
  VersionAdded: '0.2'

Minitest/AssertTruthy:
  Description: 'This cop enforces the test to use `assert(actual)` instead of using `assert_equal(true, actual)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-truthy'
  Enabled: true
  VersionAdded: '0.2'

Minitest/RefuteNil:
  Description: 'This cop enforces the test to use `refute_nil` instead of using `refute_equal(nil, something)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-nil'
  Enabled: true
  VersionAdded: '0.2'

Minitest/RefuteEmpty:
  Description: 'This cop enforces to use `refute_empty` instead of using `refute(object.empty?)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-empty'
  Enabled: true
  VersionAdded: '0.3'

Minitest/RefuteIncludes:
  Description: 'This cop enforces the test to use `refute_includes` instead of using `refute(collection.include?(object))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-includes'
  Enabled: true
  VersionAdded: '0.3'

Minitest/RefuteFalse:
  Description: 'Check if your test uses `refute(actual)` instead of `assert_equal(false, actual)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-false'
  Enabled: true
  VersionAdded: '0.3'
