Minitest:
  Include:
    - '**/test/**/*'

Minitest/AssertNil:
  Description: 'This cop enforces the test to use `assert_nil` instead of using `assert_equal(nil, something)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-nil'
  Enabled: true
  VersionAdded: '0.1'

Minitest/AssertEmpty:
  Description: 'This cop enforces the test to use `assert_empty` instead of using `assert(object.empty?)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-empty'
  Enabled: true
  VersionAdded: '0.2'

Minitest/AssertEqual:
  Description: 'This cop enforces the test to use `assert_equal` instead of using `assert(expected == actual)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-equal-arguments-order'
  Enabled: true
  VersionAdded: '0.4'

Minitest/AssertIncludes:
  Description: 'This cop enforces the test to use `assert_includes` instead of using `assert(collection.include?(object))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-includes'
  Enabled: true
  VersionAdded: '0.2'

Minitest/AssertRespondTo:
  Description: 'This cop enforces the test to use `assert_respond_to(object, :some_method)` over `assert(object.respond_to?(:some_method))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-responds-to-method'
  Enabled: true
  VersionAdded: '0.3'

Minitest/AssertTruthy:
  Description: 'This cop enforces the test to use `assert(actual)` instead of using `assert_equal(true, actual)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#assert-truthy'
  Enabled: true
  VersionAdded: '0.2'

Minitest/RefuteEqual:
  Description: 'Check if your test uses `refute_equal` instead of `assert(expected != object)` or `assert(! expected == object))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-equal'
  Enabled: true
  VersionAdded: '0.3'

Minitest/RefuteNil:
  Description: 'This cop enforces the test to use `refute_nil` instead of using `refute_equal(nil, something)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-nil'
  Enabled: true
  VersionAdded: '0.2'

Minitest/RefuteEmpty:
  Description: 'This cop enforces to use `refute_empty` instead of using `refute(object.empty?)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-empty'
  Enabled: true
  VersionAdded: '0.3'

Minitest/RefuteIncludes:
  Description: 'This cop enforces the test to use `refute_includes` instead of using `refute(collection.include?(object))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-includes'
  Enabled: true
  VersionAdded: '0.3'

Minitest/RefuteRespondTo:
  Description: 'This cop enforces the test to use `refute_respond_to(object, :some_method) over `refute(object.respond_to?(:some_method))`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-respond-to'
  Enabled: true
  VersionAdded: '0.4'

Minitest/RefuteFalse:
  Description: 'Check if your test uses `refute(actual)` instead of `assert_equal(false, actual)`.'
  StyleGuide: 'https://github.com/rubocop-hq/minitest-style-guide#refute-false'
  Enabled: true
  VersionAdded: '0.3'
